const MIXED_CHECKPOINT_ID_LIST = [
  // Versicherungs-/Dokument-/Upload-Mixed
  "AU_MISSING_EGK",
  "PRESCRIPTION_INSURANCE_PROOF_MISSING",
  "REFERRAL_INSURANCE_PROOF_MISSING",
  "APPOINTMENT_INSURANCE_PROOF_MISSING",
  "ONBOARDING_GKV_DOCUMENT_MISSING",
  "ONBOARDING_PKV_PAS_MISSING",
  "BILLING_DOCUMENT_MISSING",
  "HMV_PREVIOUS_ORDER_MISSING",
  "HMV_INFO_MISSING",
  "MEDICAL_DOCUMENT_INFO_MISSING",

  // Booking-/Routing-Mixed
  "HMV_IN_PERSON_REQUIRED",
  "MEDICAL_DOCUMENT_CONSULTATION_REQUIRED",
  "APPOINTMENT_WRONG_TYPE",
  "APPOINTMENT_BOOKING_CODE_REQUIRED",
  "IMMUNIZATION_STANDARD_AVAILABLE",
  "IMMUNIZATION_RISK_REVIEW_REQUIRED",
  "SAMPLE_COLLECTION_ORDER_AVAILABLE",

  // Lab-/Routing-Mixed
  "LAB_CHECKUP_RULES",
  "LAB_MPU_EXCLUSION",

  // Billing-/Payment-Mixed
  "BILLING_COST_NOT_COVERED",
  "BILLING_EXTERNAL_RESPONSIBILITY",
  "BILLING_ADDRESS_MISSING",
  "MEDICAL_DOCUMENT_PRIVATE_SERVICE",

  // Weitere bestaetigte Mixed
  "INFECTIOUS_PROTOCOL",
  "PRESCRIPTION_STATUTORY_POSSIBLE",
  "PRESCRIPTION_NO_PRESCRIPTION_REQUIRED",
] as const;

export type MixedCheckpointId = (typeof MIXED_CHECKPOINT_ID_LIST)[number];

export const MIXED_CHECKPOINT_IDS = MIXED_CHECKPOINT_ID_LIST;

const MIXED_CHECKPOINT_ID_SET: ReadonlySet<string> = new Set(
  MIXED_CHECKPOINT_ID_LIST,
);

export function isMixedCheckpointId(id: string): id is MixedCheckpointId {
  return MIXED_CHECKPOINT_ID_SET.has(id);
}
