// Zentrale Bindung: Welche reinen Prozess-Checkpoints werden pro Profil zusätzlich eingespeist?
// Nur risikoarme, reine Prozess-IDs (keine Mixed, keine Trigger-only, keine fachlichen IDs)

export const PROCESS_SHELF_PROFILE_BINDINGS: Record<string, readonly string[]> = {
  AU: [
    "AU_MISSING_QUESTIONNAIRE",
    "TECH_UPLOAD_FAILED",
  ],
  PRESCRIPTION: [
    "PRESCRIPTION_MEDICATION_UNCLEAR",
    "PRESCRIPTION_DOSAGE_UNCLEAR",
    "PRESCRIPTION_MEDICATION_NOT_DOCUMENTED",
    "PRESCRIPTION_SPECIALIST_REPORT_REQUIRED",
    "HOSPITAL_DISCHARGE_REPORT_MISSING",
    "TECH_UPLOAD_FAILED",
  ],
  REFERRAL: [
    "REF_SPECIALTY_REQUIRED",
    "TECH_UPLOAD_FAILED",
  ],
  LAB: [
    "LAB_RESULTS_PENDING",
    "LAB_INTERNAL_ORDER_MISSING",
    "LAB_SPECIALIST_REFERRAL_ORIGINAL_REQUIRED",
  ],
  SAMPLE_COLLECTION: [
    "SAMPLE_COLLECTION_INFORMATION_INCOMPLETE",
    "SAMPLE_COLLECTION_ORDER_UNCLEAR_OR_MISSING",
  ],
  APPOINTMENT: [
    "APPOINTMENT_DATA_INCOMPLETE",
    "APPOINTMENT_REASON_UNCLEAR",
    "APPOINTMENT_PROCESS_MULTI_STEP",
    "APPOINTMENT_PREPARATION_REQUIRED",
    "APPOINTMENT_DOCUMENT_MISSING",
    "APPOINTMENT_VIDEO_REQUIREMENTS",
  ],
  ONBOARDING: [
    "ONBOARDING_DOCTOLIB_INFO",
    "ONBOARDING_DATA_UPDATE_REQUIRED",
    "ONBOARDING_DOCUMENT_MISSING",
    "ONBOARDING_PROCESS_REQUIRED",
    "INSURANCE_NUMBER_INVALID_FORMAT",
  ],
  BILLING: [
    "BILLING_EXTERNAL_PROVIDER",
    "BILLING_INVOICE_TIMING",
    "BILLING_DATA_MISSING",
  ],
  MEDICAL_DOCUMENTS: [
    "MEDICAL_DOCUMENT_DOCUMENTATION_MISSING",
    "MEDICAL_DOCUMENTS_TRANSLATION_REQUIRED",
    "MEDICAL_DOCUMENT_PROCESS_INFO",
  ],
  TECH_SUPPORT: [
    "TECH_VIDEO_NOT_WORKING",
    "TECH_UPLOAD_FAILED",
  ],
};
